
project_id = "zpuhcukjltbjrmapkwur"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[ingest]
enabled = false

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true

[functions.download]
verify_jwt = false

[edge_runtime]
policy = "per_worker"
