// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpuhcukjltbjrmapkwur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwdWhjdWtqbHRianJtYXBrd3VyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NjM3NDYsImV4cCI6MjA2MzMzOTc0Nn0.iDf7HfkRLfH8CwIWsLl2Ac7NHsqtDvsrKnhyGJb9lRQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);